[package]
name = "vvb"
version = "0.1.0"
authors = ["Simon Gellis <simongellis@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
jni = "0.17.0"

[build-dependencies]
gl_generator = "0.14.0"

[lib]
name = "vvb"
crate-type = ["dylib"]