[package]
name = "vvb"
version = "0.1.0"
authors = ["Simon Gellis <simongellis@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
android_logger = "0.9.0"
cgmath = "0.17.0"
jni = "0.17.0"
log = "0.4.11"
paste = "1.0.0"

[build-dependencies]
gl_generator = "0.14.0"

[lib]
name = "vvb"
crate-type = ["dylib"]