[package]
name = "vvb"
version = "0.1.0"
authors = ["Simon Gellis <simongellis@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
android_logger = "0.9.0"
anyhow = "1.0.32"
cgmath = "0.17.0"
jni = "0.17.0"
log = "0.4.11"
num-traits = "0.2.14"
paste = "1.0.0"
ringbuf = "0.2.2"

[target.'cfg(target_os = "android")'.dependencies]
oboe = "0.4.2"
oboe-sys = "0.4.2"

[build-dependencies]
gl_generator = "0.14.0"

[lib]
name = "vvb"
doctest = false
crate-type = ["rlib", "dylib"]

[[bin]]
name = "perftest"
test = false
path = "src/emulator/main.rs"

[profile.release]
debug = true
